Initial buildout
pjhartzell/chesapeake pull request #1
Opened 2022-04-21 14:04 UTC by pjhartzell

**Description:**
Initial buildout of the package.

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [x] Documentation has been updated to reflect changes, if applicable.
- [x] Changes are added to the [CHANGELOG](../CHANGELOG.md).
- [x] Examples are added to `examples/`

2022-04-21 21:48 UTC, gadomski requested changes

2022-04-21 21:48 UTC, gadomski commented on README.md
> +# stactools-chesapeake
Have you talked about the `chesapeake` name with other folks on the PC? My instinct is that its too general -- maybe `chesapeake-lulc` to match how we're doing `drcog-lulc`?

2022-04-21 21:48 UTC, gadomski commented on README.md
> +$ stac chesapeake create-item <source-cog-file> <output-directory> <collection-id>
I see why `create-item` needs a collection ID; is there any way to guess the collection from the data? Any TIFF tags? Its not the end of the world to have to provide it, but it is a little clunky.

2022-04-21 21:48 UTC, gadomski commented on examples/chesapeake-lc-13/Baywide_13Class_20132014_E1300000_N1770000/Baywide_13Class_20132014_E1300000_N1770000.json
> +  },
This geometry doesn't look like it matches the `proj:transform` and `proj:shape` information.

2022-04-21 21:48 UTC, gadomski commented on examples/chesapeake-lc-7/collection.json
> +    "chesapeake conservancy"
Different keywords than the 13 class version, is this intentional?

2022-04-21 21:48 UTC, gadomski commented on setup.cfg
>  author = Presotn Hartzell
```suggestion
author = Preston Hartzell
```

2022-04-21 21:48 UTC, gadomski commented on src/stactools/chesapeake/fragments/chesapeake-lc-13/asset.json
> +      "description": "Aberdeen Proving Ground",
LOL this cracks me up. Sorry not a useful comment.

2022-04-21 21:48 UTC, gadomski commented on src/stactools/chesapeake/stac.py
> +            f"of {', '.join(constants.COLLECTION_IDS)}")
Could move this check to `StacFragments.__init__`?

2022-04-21 21:48 UTC, gadomski commented on src/stactools/chesapeake/utils.py
>          args.append(outfile)
Is there any way to use rasterio to do the subsetting? Calling out to system `gdal_translate` is just a bit more fragile and it'd be good to avoid if we can.

2022-04-21 21:48 UTC, gadomski commented on src/stactools/chesapeake/utils.py
> +         left_bottom: Tuple[(int, int)],
I _think_ this should be `Tuple[int, int]`.

2022-04-21 21:48 UTC, gadomski commented on src/stactools/chesapeake/utils.py
> +def remove_nodata(indir: str) -> None:
Can you add an `nodata_dir: Optional[str]` argument in case you want to move the nodata tifs out of the directory entirely?

2022-04-21 22:23 UTC, pjhartzell commented on README.md
> +# stactools-chesapeake
Hmm. Nope, did not talk with the PC folks. Didn't think this would matter to them. I did make the choice based on the fact they named the container for the data "chesapeake", though 🙂 . But agreed on it being general. 

Reviewing the stactools package names, typically they spec either a sensor or organization - "chesapeake" is neither. Maybe revert back to something like `cc-lulc`, where cc stands for "Chesapeake Conservancy"? Technically it is the Chesapeake Conservancy Conservation Innovation Center that is the lead on this. But a `cccic` prefix is a lot of c's. Of course, none of this tells us where the data area is, which is the Chesapeake Bay watershed.

I don't have strong feelings on this. So if `chesapeake-lulc` is good, I'm cool with that.

2022-04-21 23:38 UTC, pjhartzell commented on README.md
> +$ stac chesapeake create-item <source-cog-file> <output-directory> <collection-id>
Yep, we can get it from the filenames. I'll make that change. No TIFF tags with this data, unfortunately.

2022-04-21 23:39 UTC, pjhartzell commented on examples/chesapeake-lc-7/collection.json
> +    "chesapeake conservancy"
No, that's a mistake. Thanks.

2022-04-21 23:39 UTC, pjhartzell commented on setup.cfg
>  author = Presotn Hartzell
Yep, that gets me all the time.

2022-04-21 23:40 UTC, pjhartzell commented on src/stactools/chesapeake/fragments/chesapeake-lc-13/asset.json
> +      "description": "Aberdeen Proving Ground",
Yeah. Only reason I can think of is that they didn't want their land mass classified?

2022-04-21 23:41 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
> +         left_bottom: Tuple[(int, int)],
Hmm. That should have been corrected already. I'll get that patched.

2022-04-21 23:58 UTC, pjhartzell commented on examples/chesapeake-lc-13/Baywide_13Class_20132014_E1300000_N1770000/Baywide_13Class_20132014_E1300000_N1770000.json
> +  },
I'm not clear on this. The geometry is in wgs84 (per stac spec) and proj:transform and proj:shape describe the projected raster coordinates and shape. I believe that is the way it should be, no?

2022-04-21 23:59 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
> +def remove_nodata(indir: str) -> None:
yep.

2022-04-22 00:03 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
>          args.append(outfile)
I think so.

I actually see another booger that makes me wonder if my tiling worked correctly. I include `-a_nodata` in the gdal_translate call twice if I pass a `nodata` value.

2022-04-22 10:33 UTC, gadomski commented on README.md
> +# stactools-chesapeake
> So if `chesapeake-lulc` is good, I'm cool with that.

`chesapeake-lulc` feels like the best to me. I don't think I'd ever type `cccic-lulc` correctly, and `cc-lulc` looks like a SPDX license identifier :-P.

2022-04-22 10:47 UTC, gadomski commented on examples/chesapeake-lc-13/Baywide_13Class_20132014_E1300000_N1770000/Baywide_13Class_20132014_E1300000_N1770000.json
> +  },
Totally ignore me, I'm just out of practice w/ 1m resolution data :-D.

2022-04-22 10:48 UTC, gadomski commented on src/stactools/chesapeake/fragments/chesapeake-lc-13/asset.json
> +      "description": "Aberdeen Proving Ground",
musta been

2022-04-22 12:19 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
> +def remove_nodata(indir: str) -> None:
done

2022-04-22 12:20 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
> +         left_bottom: Tuple[(int, int)],
done

2022-04-22 12:20 UTC, pjhartzell commented on examples/chesapeake-lc-7/collection.json
> +    "chesapeake conservancy"
fixed.

2022-04-22 12:21 UTC, pjhartzell commented on setup.cfg
>  author = Presotn Hartzell
corrected.

2022-04-22 12:23 UTC, pjhartzell commented on README.md
> +# stactools-chesapeake
`chesapeake-lulc` for the win! I'd prefer to make this change after merging this PR. Sound OK?

2022-04-22 12:29 UTC, gadomski commented on README.md
> +# stactools-chesapeake
Yup! Opened https://github.com/pjhartzell/chesapeake/issues/2 to track.

2022-04-22 12:55 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
>          args.append(outfile)
Fixed the error with the hardcoded nodata value of 0. Regarding the request to move to rasterio, yes, it looks like this can be done. But requesting to merge this PR without this enhancement for now and add it as an issue. I'd like to merge shortly so I can test my ETL. I plan to complete this today.

2022-04-22 13:00 UTC, pjhartzell commented on src/stactools/chesapeake/stac.py
> +            f"of {', '.join(constants.COLLECTION_IDS)}")
love me some `dry`. Yep and done.

2022-04-22 13:05 UTC, gadomski commented on src/stactools/chesapeake/utils.py
>          args.append(outfile)
REQUEST GRANTED :-D can you drop a link to that issue in this comment chain please and thanks!

2022-04-22 13:31 UTC, pjhartzell commented on README.md
> +$ stac chesapeake create-item <source-cog-file> <output-directory> <collection-id>
done.

2022-04-22 13:35 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
>          args.append(outfile)
ACKNOWLEDGED. 🙂  Issue added with link.

2022-04-22 13:40 UTC, gadomski requested changes

2022-04-22 13:40 UTC, gadomski commented on src/stactools/chesapeake/utils.py
> +            only nodata values.
This isn't optional in the function signature.

2022-04-22 13:53 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
> +            only nodata values.
Yeah, [I moved the option to the command](https://github.com/pjhartzell/chesapeake/pull/1/files#diff-45149b47b4521c7333a2ebe60f2087d35845eb27677eba5f6fc7aaf3dec26e7dR66), which also creates the default folder if the option is not passed. Failed to communicate that. Any downsides to this?

2022-04-22 13:55 UTC, gadomski commented on src/stactools/chesapeake/utils.py
> +            only nodata values.
I think that's fine -- docs just need an update.
```suggestion
        nodata_dir (str): Directory to move TIF files that contain only nodata values.
```

2022-04-22 14:01 UTC, pjhartzell commented on src/stactools/chesapeake/utils.py
> +            only nodata values.
Sounds good. Docs updated in several places.

2022-04-22 14:12 UTC, merged